using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Rpc.Generator;

[Generator]
public sealed class RpcSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var rpcInterfaces = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is InterfaceDeclarationSyntax iface &&
                    iface.AttributeLists.Count > 0,
                transform: static (ctx, _) => GetRpcInterface(ctx))
            .Where(static m => m != null)
            .Select(static (m, _) => m!);

        context.RegisterSourceOutput(rpcInterfaces, static (spc, iface) =>
            GenerateDispatcher(spc, iface));
    }

    private static INamedTypeSymbol? GetRpcInterface(GeneratorSyntaxContext ctx)
    {
        var syntax = (InterfaceDeclarationSyntax)ctx.Node;
        var symbol = ctx.SemanticModel.GetDeclaredSymbol(syntax) as INamedTypeSymbol;
        if (symbol == null) return null;

        return symbol.GetAttributes().Any(a =>
            a.AttributeClass?.Name == "RpcServiceAttribute") ? symbol : null;
    }

    private static void GenerateDispatcher(SourceProductionContext ctx, INamedTypeSymbol iface)
    {
        var sb = new StringBuilder();
        var ns = iface.ContainingNamespace.ToDisplayString();
        var name = iface.Name.TrimStart('I');

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using ServerLib.Interface;");
        sb.AppendLine("using ServerLib.Core.Rpc;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        sb.AppendLine($"public sealed partial class {name}Dispatcher : RpcDispatcher");
        sb.AppendLine("{");
        sb.AppendLine($"    private readonly {iface.ToDisplayString()} _handler;");
        sb.AppendLine();
        sb.AppendLine($"    public {name}Dispatcher({iface.ToDisplayString()} handler) : base()");
        sb.AppendLine("    {");
        sb.AppendLine("        _handler = handler;");

        foreach (var method in iface.GetMembers().OfType<IMethodSymbol>())
        {
            var attr = method.GetAttributes()
                .FirstOrDefault(a => a.AttributeClass?.Name == "RpcMethodAttribute");
            if (attr == null) continue;

            var packetId = (ushort)(int)attr.ConstructorArguments[0].Value!;
            sb.AppendLine($"        Register({packetId}, async (session, payload, ct) =>");
            sb.AppendLine($"            await _handler.{method.Name}Async(session, payload, ct));");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        ctx.AddSource($"{name}Dispatcher.g.cs", sb.ToString());
    }
}
